AY2324S1-CS2103T-T10-2/tp

build.gradle
-   [x] Bug Fix
-   This PR is a documentation update (chore) that addresses issues with the build.gradle file. The previous implementation caused errors in running cross OS after compilation on Mac OS, so the contents of the file have been modified to utilize Gradle dependencies for JavaFX, ensuring smoother and more reliable build processes.
-   https://github.com/nus-cs2103-AY2324S1/forum/issues/159
-   [x] Yes
=> chore: Edit build gradle file

README.md, docs/_config.yml, docs/_sass/minima/_base.scss, docs/index.md
-   Replace traces of AB-3 with CoordiMate
-   Update README and index.md
-   Addresses #37 
-   [ ] Yes
-   [x] No, and this is why: See deployment: https://docs-update-readme.coordimate.pages.dev/
=> docs: Update README, config.yml and index.md

docs/DeveloperGuide.md
-   Updated User Stories for deletePerson, addTask and updating of GUI
-   Created Use Cases for deletePerson and addTask
-   Partially resolves [Update Developer Guide](https://github.com/AY2324S1-CS2103T-T10-2/tp/issues/39)
-   [ ] Yes
-   [X] No, and this is why: [Visit website](https://docs-developer-guide-v1-1.coordimate.pages.dev/DeveloperGuide)
=> docs: Update DG to reflect user stories and use cases

docs/UserGuide.md
Moving my changes from draft UG to actual UG.
-   Related Issue #38 
-   [x] No, and this is why: Check deployment [here](https://docs-ug-v1-1.coordimate.pages.dev/UserGuide).
=> chore: Move changes to UG

docs/UserGuide.md
Moving my changes from draft UG to actual UG.
-   Related Issue #38 
-   [ ] Yes
-   [X] No, and this is why: Deployed [here](https://docs-ug-v1-1.coordimate.pages.dev/UserGuide)
=> chore: Move changes from draft UG to actual UG

docs/UserGuide.md
-   Moving my changes from draft UG to actual UG.
-   Related Issue #38 
-   [ ] Yes
-   [x] No, and this is why: See deployment
=> chore: Update UG with final format from draft UG

docs/UserGuide.md
-   Copy deletePerson and addTask from DraftUG to UG
-   Related Issue #38 
-   [ ] Yes
-   [X] No, and this is why: See deployment
=> docs: Copy over DraftUG to UG

docs/UserGuide.md
I noticed that the dashboard did not mark our UG as fully adapted. I've erased all instances of "AddressBook" in our UG. 
Side effect is that some given file names are wrong. But I think that's not a big issue for now. The priority should be to appease the tracker.
None
-   [x] No, and this is why: [Deployment](https://docs-ug-v1-1.coordimate.pages.dev/UserGuide)
=> docs: Remove all traces of AB3 in UG

src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpWindow.css, src/main/resources/view/HelpWindow.fxml
* Update link for help message
* Add open-in-browser button
[Here's a screen recording.](https://github.com/AY2324S1-CS2103T-T10-2/tp/files/12856764/Screen.Recording.2023-10-10.at.19.47.20.zip)
-   Related Issue #30 
-   [x] No, there are UI changes that I'm unable to cover.
There is some new Java code to open the link in browser. Not sure how to test this out without some fancy framework, but I don't think we should be doing that much.
P.S. Charisma said it's okay to leave UI changes untested. 🤔
=> feat: Update help command

src/main/java/seedu/address/model/task/Note.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/task/Title.java, src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java, src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java, src/test/java/seedu/address/model/task/NoteTest.java, src/test/java/seedu/address/model/task/TaskTest.java, src/test/java/seedu/address/model/task/TitleTest.java
* Add Task class, which consists of a Title and Note
* Implement hashCode() override for Task, Title and Note
* Add tests for Task, Title and Note
* Refactor assertTrue() to assertEquals() in tests
-   Smaller version of PR: #79
-   [x] Yes
=> feat: Add Task Classes

src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/ReadOnlyAddressBook.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/task/UniqueTaskList.java, src/main/java/seedu/address/storage/JsonAdaptedTask.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidTaskAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/task/UniqueTaskListTest.java, src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java, src/test/java/seedu/address/testutil/TaskBuilder.java, src/test/java/seedu/address/testutil/TypicalTasks.java
-  Automatically load tasks from JSON file into ModelManager
- Add tests to test loading of JSON files for tasks
- Update JSON files to support tasks
- Add TaskBuilder and TypicalTasks testing utils
PS: As the UI is not done up yet, please manually load a JSON file and use the debugger to verify.
TODO:
- Add more tests to UniqueTaskListTest
-   Related Issue #36
- Smaller version of #79 
-   [x] Yes
-   [x] I need help with writing tests (for …
=> feat: Implement tasks storage

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/MessagesTest.java, src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java, src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/ModelStub.java, src/test/java/seedu/address/testutil/TaskUtil.java
-   Related Issue #31 
-   [x] Yes, it was a pain.
=> feat: addTask command

src/main/java/seedu/address/logic/commands/ListPersonCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
-   Replaced instances of `list` with `listPerson`
-   Related Issue #51 
-   [X] Yes
=> feat: Implement listPerson command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/task/NoteContainsKeywordsPredicate.java, src/main/java/seedu/address/model/task/TaskContainsKeywordsPredicate.java, src/main/java/seedu/address/model/task/TitleContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java, src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java, src/test/java/seedu/address/model/task/NoteContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/task/TaskContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/task/TitleContainsKeywordsPredicateTest.java
* Add TaskContainsKeywordsPredicate class to check if a Task's title or note contains a keyword
---
* Update ModelStub in AddPersonCommandTest
* Expand Javadocs
* Add long line breaks for separation between methods
---
* Add FindTaskCommand and FindTaskCommandParser
* Update Messages with result message
---
* Ensure AddressBookParser can parse find task commands
* Fix minor typo in FindTaskCommandTest
-  Resolves #35 
- Supersedes PR #80 
-   [x] Yes
-   [ ] No, there are UI changes that I'm unable …
=> feat: Implement Find Task

.gitignore
-   [x] Refactor
I use VSCode sometimes and it generates a bunch of bin files. Each time I have to manually ignore them during my git add, but it's starting to annoy me. So let's just gitignore it.
None
-   [x] No, and this is why: why
=> chore: Ignore bin files

src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml
-   Wrap text in result display.
-   Make result display adjustable.
-   Related Issue #65 
-   [ ] Yes
-   [X] No, there are UI changes that I'm unable to cover.
=> feat: Update UI for Result Display Box

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/EditTaskCommand.java, src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedTask.java, src/main/java/seedu/address/ui/TaskCard.java, src/main/resources/view/TaskListCard.fxml, src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json, src/test/java/seedu/address/logic/MessagesTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java, src/test/java/seedu/address/model/task/TaskTest.java, src/test/java/seedu/address/model/task/UniqueTaskListTest.java, src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java, src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java, src/test/java/seedu/address/testutil/TaskBuilder.java, src/test/java/seedu/address/testutil/TaskUtil.java, src/test/java/seedu/address/testutil/TypicalTasks.java
-   Add tag to task and the necessary tests.
-   Related Issue #97 
-   [X] Yes
=> feat: Add tag to task

docs/UserGuide.md, src/main/java/seedu/address/model/util/SampleDataUtil.java
-   Update the tags in the task.
-   Update the screenshots for deletePerson, deleteTask.
-   Related Issue #65 
-   [ ] Yes
-   [X] No, and this is why: these are documentation updates in UG
=> docs: Update UG

build.gradle
-   Add assertions to build.gradle 
-   None
-   [ ] Yes
-   [x] No, and this is why: edits to configuration only
=> chore: Add assertions to build gradle file

src/main/java/seedu/address/logic/commands/ListTagCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/java/seedu/address/model/tag/TagFrequencyTable.java, src/test/java/seedu/address/logic/commands/ListTagCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/ModelStub.java, src/test/java/seedu/address/model/tag/TagFrequencyTableTest.java, src/test/java/seedu/address/model/tag/TagTest.java
-   Make Tags comparable
-   Closes #95
-   [x] Yes
=> feat: Implement list tags command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindTagCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FindTagCommandParser.java, src/main/java/seedu/address/model/person/PersonContainsTagsPredicate.java, src/main/java/seedu/address/model/task/TaskContainsTagsPredicate.java, src/test/java/seedu/address/logic/commands/FindTagCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java, src/test/java/seedu/address/model/person/PersonContainsTagsPredicateTest.java, src/test/java/seedu/address/model/task/TaskContainsTagsPredicateTest.java
-   Added new command for findTag which takes in arbitrary number of keyword(s) (i.e. tags) to display all persons and tasks with at least one of the keyword(s).
-   Related Issue #104 
-   [X] Yes
=> feat: Implement findTag

src/main/java/seedu/address/logic/commands/AddPersonCommand.java, src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/DeleteAllPersonCommand.java, src/main/java/seedu/address/logic/commands/DeleteAllTaskCommand.java, src/main/java/seedu/address/logic/commands/DeletePersonCommand.java, src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java, src/main/java/seedu/address/logic/commands/EditPersonCommand.java, src/main/java/seedu/address/logic/commands/EditTaskCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/FindDoneCommand.java, src/main/java/seedu/address/logic/commands/FindNotDoneCommand.java, src/main/java/seedu/address/logic/commands/FindPersonCommand.java, src/main/java/seedu/address/logic/commands/FindTagCommand.java, src/main/java/seedu/address/logic/commands/FindTaskCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ListPersonCommand.java, src/main/java/seedu/address/logic/commands/ListTagCommand.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/commands/MarkTaskCommand.java, src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TaskUtil.java
- Add shortened command words for all commands.
-   Related Issue #105 
-   [x] Yes
=> feat: Shorten commands

src/main/java/seedu/address/logic/commands/ListAllCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/ListAllCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
-  feat: Implement listAll command
-   Closes #111
-   [x] Yes
=> feat: Implement listAll command

src/main/java/seedu/address/logic/commands/DeleteTagPersonCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteTagPersonCommandParser.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteTagPersonCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTagPersonCommandParserTest.java
Add the `deleteTagPerson` command. For the sake of review readability, I will implement `deleteTagTask` in a separate PR, but the code will be very similar.
-   Related Issue #119 
-   [ ] Yes
-   [x] No, and this is why: soon
=> feat: Add DeleteTagPerson command

src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java, src/main/java/seedu/address/logic/commands/AddTagTaskCommand.java, src/main/java/seedu/address/logic/parser/AddTagPersonCommandParser.java, src/main/java/seedu/address/logic/parser/AddTagTaskCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/AddTagPersonCommandTest.java, src/test/java/seedu/address/logic/commands/AddTagTaskCommandTest.java, src/test/java/seedu/address/logic/parser/AddTagPersonCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddTagTaskCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TaskBuilder.java
-   This feature allows users to add tags on top of the current list of tags.
-   Related Issue #113 
-   [X] Yes
=> feat: Implement addTagTask and addTagPerson commands

src/main/java/seedu/address/logic/commands/DeleteAllDoneCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/DeleteAllDoneCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/ModelStub.java
-   Add feature to delete all done tasks.
-   Related Issue #114 
-   [x] Yes
-   [ ] No, and this is why: 
=> feat: Add delete all done tasks

src/main/java/seedu/address/MainApp.java
-   Bump Version number
- Set early access to false
-   Related Issue #
-   [ ] Yes
-   [x] No, and this is why: 
=> chore: Bump version number to 1.3.0

docs/team/m1oojv.md
-   Update portfolio page to list out all my contributions done towards CoordiMate
-   Related Issue #154 
-   [ ] Yes
-   [x] No, and this is why: Documentation changes
=> docs: Update Megan's PPP

docs/team/pra-navi.md
-   Update Pranavi's PPP.
-   Related Issue #155 
-   [ ] Yes
-   [X] No, and this is why: Docs
=> docs: Update Pranavi's PPP

docs/team/hugenoob.md
-   Add my PPP details.
-   Resolves #152 
-   [x] No, and this is why: no
=> docs: Update Lingxi's PPP

docs/team/freshcabbage123.md
-   Update PPP
-   Closes #153 
-   [ ] Yes
-   [X] No, and this is why: Docs
=> docs: Update Alan's PPP

docs/team/jiakai-17.md
-    Update PPP Page
-   Closes #151 
-   [ ] Yes
-   [x] No, and this is why: Docs
PDF Preview: 
[jk-ppp.pdf](https://github.com/AY2324S1-CS2103T-T10-2/tp/files/13266873/jk-ppp.pdf) (Edge, A4, 89%)
=> docs: Update Jiakai's PPP Page

README.md
Sync the project README with the UG intro.
None
-   [ ] No, and this is why: no
=> docs: Update repo README

docs/AboutUs.md
Add responsibilities in AboutUs
None
-   [ ] No, and this is why: docs
=> docs: Update AboutUs

docs/team/jiakai-17.md
- Remove page break
- Shorten some explanations
- Add some enhancements
-   Related Issue #
-   [ ] Yes
-   [x] No, and this is why: docs
=> docs: Reformat PPP to fit page limit at default zoom level

docs/team/hugenoob.md
Cut PPP to fit max length of 2 pages.
None
-   [x] No, and this is why: docs
=> docs: Cut PPP length

docs/team/pra-navi.md
-   Remove page break.
-   Related Issue #
-   [ ] Yes
-   [X] No, and this is why: PPP update
=> fix: Remove page break in PPP

docs/team/freshcabbage123.md
-  Remove square bracket
-  Remove tools section
-   Related Issue #
-   [ ] Yes
-   [X] No, and this is why: docs
=> docs: Reformat Alan's PPP
